RealEstateMarket/Assignment02/Models/Brokerage.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealEstateMarket.Models
{
    public class Brokerage
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Registration Number")]
        [Required]
        public string Id { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string Title { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Fee { get; set; }

        public ICollection<Subscription>? Subscriptions { get; set; }

        public ICollection<Advertisement>? Advertisements { get; set; }

        // overrides get hash code function to compare Brokerages by Id
        public override int GetHashCode()
        {
            return this.Id.GetHashCode();
        }

        // overrides Equal function to compare Brokerages by Id -
        // for use in client subscriptions and splitting brokerages into ones scubscribed to and ones unsubscribed to with Except()
        public override bool Equals(object? objEval)
        {
            if (objEval is not Brokerage)
            {
                throw new ArgumentException("Object is not a Brokerage");
            }
            
            var brokerageEval = objEval as Brokerage;

            if (brokerageEval == null)
            {
                return false;
            }
            else
            {
                return this.Id.Equals(brokerageEval.Id);
            }
        }
    }
}

RealEstateMarket/Assignment02/Models/ViewModels/BrokeragesViewModel.cs
namespace RealEstateMarket.Models.ViewModels
{
    public class BrokeragesViewModel
    {
        public IEnumerable<Client> Clients { get; set; }
        public IEnumerable<Brokerage> Brokerages { get; set; }
        public IEnumerable<Subscription> Subscriptions { get; set; }
        public IEnumerable<Advertisement> Advertisements { get; set;}
    }
}

RealEstateMarket/Assignment02/Controllers/AdvertisementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RealEstateMarket.Data;
using RealEstateMarket.Models;
using RealEstateMarket.Models.ViewModels;
using Azure.Storage.Blobs;
using Azure;
using System.Diagnostics;
using System.ComponentModel;

namespace RealEstateMarket.Controllers
{
    public class AdvertisementsController : Controller
    {
        private readonly MarketDbContext _context;
        private readonly BlobServiceClient _blobServiceClient;

        private readonly long _fileSizeLimit = 20000000;
        private readonly string[] permittedExtensions = { ".png", ".jpg", ".jpeg", ".gif" };
        private readonly string container = "adimages";

        public AdvertisementsController(MarketDbContext context, BlobServiceClient blobServiceClient)
        {
            _context = context;
            _blobServiceClient = blobServiceClient;
        }

        // GET: Advertisements
        public async Task<IActionResult> Index(string? Id)
        {
            if (Id != null)
            {
                // find the brokerage
                var brokerage = await _context.Brokerages
                .Include(b=>b.Advertisements)
                .SingleAsync(b => b.Id == Id);

                return View(brokerage);

            }
            else
            {
                return NotFound();
            }
        }


        // GET: Advertisements/Create
        public async Task<IActionResult> Create(string? Id)
        {
            if (Id != null)
            {
                // find the brokerage
                var brokerage = await _context.Brokerages
                .SingleAsync(b => b.Id == Id);

                return View(brokerage);
            }
            else
            {
                return NotFound();
            }
        }

        [BindProperty]
        public Advertisement Advertisement { get; set; }

        // POST: Advertisements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file, string brokerageId)
        {
            // perform validation checks
            var ext = Path.GetExtension(file.FileName).ToLowerInvariant();
            if (string.IsNullOrEmpty(ext) || !permittedExtensions.Contains(ext))
            {
                String message = "File extension must be one of ";
                foreach (string extension in permittedExtensions)
                {
                    message += extension + " ";
                }
                // Debug.WriteLine(message);
                throw new Exception(message);
            }

            if (file.Length > _fileSizeLimit || file.Length == 0)
            {
                // Debug.WriteLine("File size must be greater than 0 bytes and upto 20MB");
                throw new Exception("File size must be greater than 0 bytes and upto 20MB");
            }

            // create container client to attach to a container
            BlobContainerClient containerClient;
            try
            {
                // attempt to create a new container and make public
                containerClient = await _blobServiceClient.CreateBlobContainerAsync(container);
                containerClient.SetAccessPolicy(Azure.Storage.Blobs.Models.PublicAccessType.BlobContainer);
            }
            catch (RequestFailedException)
            {
                // container already exists
                containerClient = _blobServiceClient.GetBlobContainerClient(container);
            }

            try
            {
                string filePath = Path.GetRandomFileName();
                // create the blob to hold the data
                var blockBlob = containerClient.GetBlobClient(filePath);
                // if blob exists already throw an error
                if (await blockBlob.ExistsAsync())
                {
                    throw new Exception("Blob with specified url already exists");
                }

                Advertisement.FileName = filePath;
                Advertisement.Url = blockBlob.Uri.AbsoluteUri;

                using (var memoryStream = new MemoryStream())
                {
                    // copy the file data into memory
                    await file.CopyToAsync(memoryStream);

                    // navigate back to the beginning of the memory stream
                    memoryStream.Position = 0;

                    // send the file to the cloud
                    await blockBlob.UploadAsync(memoryStream);
                    memoryStream.Close();
                }


            }
            catch (RequestFailedException)
            {
                throw new Exception("Image blob already exists");
            }

            // find the brokerage
            var brokerage = await _context.Brokerages
            .Include(b=>b.Advertisements)
            .SingleAsync(b => b.Id == brokerageId);
            
            // add brokerage to the advertisement
            Advertisement.Brokerage = brokerage;

            // add advertisement to brokerage
            brokerage.Advertisements.Add(Advertisement);

            // update in context
            _context.Advertisements.Add(Advertisement);
            _context.Brokerages.Update(brokerage);

            // save context
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { id = brokerageId });
        }


        // GET: Advertisements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Advertisements == null)
            {
                return NotFound();
            }

            var advertisement = await _context.Advertisements
                .Include(a => a.Brokerage)
                .FirstOrDefaultAsync(m => m.AdId == id);
            if (advertisement == null)
            {
                return NotFound();
            }

            return View(advertisement);
        }


        // POST: Advertisements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int AdId)
        {
            // find the advertisement
            var advertisement = await _context.Advertisements
            .Include(b => b.Brokerage)
            .SingleAsync(b => b.AdId == AdId);
            var brokerageId = advertisement.Brokerage.Id;

            BlobContainerClient containerClient;
            try
            {
                // get the container and store container object
                containerClient = _blobServiceClient.GetBlobContainerClient(container);
            }
            catch (RequestFailedException)
            {
                throw new Exception("Container does not exist");
            }

            try
            {
                await containerClient.DeleteBlobAsync(advertisement.FileName);
            }
            catch (RequestFailedException)
            {
                throw new Exception("Specified blob does not exist");
            }

            // find the brokerage and remove ad
            //var brokerage = await _context.Brokerages
            //.Include(b => b.Advertisements)
            //.SingleAsync(b => b.Id == brokerageId);

            // brokerage.Advertisements.Remove(advertisement);

            // update in context
            // _context.Brokerages.Update(brokerage);
            _context.Advertisements.Remove(advertisement);

            await _context.SaveChangesAsync();


            return RedirectToAction("Index", new { id = brokerageId });
        }

        private bool AdvertisementExists(int id)
        {
            return _context.Advertisements.Any(e => e.AdId == id);
        }
    }
}

RealEstateMarket/Assignment02/Controllers/BrokeragesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RealEstateMarket.Data;
using RealEstateMarket.Models;
using RealEstateMarket.Models.ViewModels;

namespace RealEstateMarket.Controllers
{
    public class BrokeragesController : Controller
    {
        private readonly MarketDbContext _context;

        public BrokeragesController(MarketDbContext context)
        {
            _context = context;
        }

        // GET: Brokerages
        public async Task<IActionResult> Index(string? Id)
        {
            var viewModel = new BrokeragesViewModel
            {
                Brokerages = await _context.Brokerages
                .Include(i => i.Subscriptions)
                .ThenInclude(Subscription => Subscription.Client)
                .AsNoTracking()
                .OrderBy(i => i.Id)
                .ToListAsync()
            };

            if (Id != null)
            {
                viewModel.Subscriptions = viewModel.Brokerages.Where(
                    x => x.Id == Id).Single().Subscriptions;
            }

            return View(viewModel);
        }

        // GET: Brokerages/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Brokerages == null)
            {
                return NotFound();
            }

            var brokerage = await _context.Brokerages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brokerage == null)
            {
                return NotFound();
            }

            return View(brokerage);
        }

        // GET: Brokerages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brokerages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Fee")] Brokerage brokerage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brokerage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brokerage);
        }

        // GET: Brokerages/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Brokerages == null)
            {
                return NotFound();
            }

            var brokerage = await _context.Brokerages.FindAsync(id);
            if (brokerage == null)
            {
                return NotFound();
            }
            return View(brokerage);
        }

        // POST: Brokerages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,Fee")] Brokerage brokerage)
        {
            if (id != brokerage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brokerage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrokerageExists(brokerage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brokerage);
        }

        // GET: Brokerages/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Brokerages == null)
            {
                return NotFound();
            }

            var brokerage = await _context.Brokerages
                .Include(x => x.Advertisements)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brokerage == null)
            {
                return NotFound();
            }

            return View(brokerage);
        }

        // POST: Brokerages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string Id)
        {
            if (_context.Brokerages == null)
            {
                return Problem("Entity set 'MarketDbContext.Brokerages'  is null.");
            }

            var brokerage = await _context.Brokerages
                .Include(x => x.Advertisements)
                .FirstOrDefaultAsync(m => m.Id == Id);

            if (brokerage != null)
            {
                if (brokerage.Advertisements.Count() > 0)
                {
                    throw new Exception("Can not delete a brokerage with existing advertisements");
                }
                _context.Brokerages.Remove(brokerage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrokerageExists(string id)
        {
          return _context.Brokerages.Any(e => e.Id == id);
        }
    }
}

RealEstateMarket/Assignment02/Views/Brokerages/Create.cshtml
@model RealEstateMarket.Models.Brokerage

@{
    ViewData["Title"] = "Create Brokerage";
}

<h1>Create</h1>

<h4>Brokerage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input minlength="3" maxlength="50" asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input type="number" step="0.01" asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RealEstateMarket/Assignment02/Views/Brokerages/Delete.cshtml
@model RealEstateMarket.Models.Brokerage

@{
    ViewData["Title"] = "Delete Brokerage";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brokerage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fee)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        @if(Model.Advertisements.Count > 0)
        {
            <input type="submit" value="brokerage contains advertisements" clas s="btn btn-danger" disabled/>
        } else
        {
            <input type="submit" value="Delete" class="btn btn-danger" />
        }
         |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RealEstateMarket/Assignment02/Views/Brokerages/Details.cshtml
@model RealEstateMarket.Models.Brokerage

@{
    ViewData["Title"] = "Brokerage Details";
}

<h1>Details</h1>

<div>
    <h4>Brokerage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fee)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RealEstateMarket/Assignment02/Views/Brokerages/Edit.cshtml
@model RealEstateMarket.Models.Brokerage

@{
    ViewData["Title"] = "Edit Brokerage";
}

<h1>Edit</h1>

<h4>Brokerage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RealEstateMarket/Assignment02/Views/Brokerages/Index.cshtml
@model RealEstateMarket.Models.ViewModels.BrokeragesViewModel

@{
    ViewData["Title"] = "Brokerages Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Fee
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Brokerages)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fee)
                </td>
                <td>
                    <a asp-action="Index" asp-route-id="@item.Id">Select</a> |
                    <a asp-controller="Advertisements" asp-action="Index" asp-route-id="@item.Id">Ads</a> |
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.Subscriptions != null)
{
    <h3>
        Subscribers to the brokerage
    </h3>
    <table class="table">
        <tr>
            @if (Model.Subscriptions.Count() > 0)
            {
                <th> Name </th>
            }
            else
            {
                <th> No subscriptions exist </th>
            }
        </tr>
        @foreach (var item in Model.Subscriptions)
        {
            <tr>
                <td>
                    @item.Client.FullName
                </td>
            </tr>
        }
    </table>
}